### ISSUE TITLE
RN Android : CallControls missing after returning to call with PiP

### ISSUE THREAD

**Issue by mccraigmccraig** [GetStream/stream-video-js#1663]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-sdk`
- [x] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
On Android, with PiP enabled, the PiP itself works fine but on returning to our app the CallControls have disappeared

**To Reproduce**

- Make a video call to an Android phone with PiP enabled
- send the app to the background
- return to the app via the PiP
- CallControls have disappeared

**Expected behavior**
CallControls shoud be restored after the app returns to the foreground

**Screenshots**

https://www.loom.com/share/55095a0feef74938be800a40c89252a4

**Version**

- @stream-io/video-react-native-sdk: 1.9.14
- @stream-io/react-native-webrtc: 125.0.4

**Env:**

**React Native**
- RN: 0.72.4
- OS: [e.g. iOS, linux...] - Android 15
- Device or emulator [e.g. android emulator, real iPhone X...] - Pixel 8

**Additional context**
n/a

**Comment by kristian-mkd** [comment]
Hi @mccraigmccraig, thanks for reporting, we will take a look at the issue.

**Comment by kristian-mkd** [comment]
Hi @mccraigmccraig, I could not reproduce the issue on two different devices with different android versions. Can you tell me if this happens on every try for you or maybe it was some one time glitch?

**Comment by mccraigmccraig** [comment]
Hi @kristian-mkd , it's happening on every try on my Pixel-8/Android-15 ... 🤔 I'll get some colleagues to try some different devices

**Comment by mccraigmccraig** [comment]
we're also currently stuck on RN `0.72.4`... I've no idea if that has any bearing on the problem

**Comment by santhoshvai** [comment]
@mccraigmccraig That should not be causing it. We use kotlin 1.7 to stay supported with 0.72. Do you see anything in your native android logs? Can you please share them here if possible.

**Comment by santhoshvai** [comment]
Hey @mccraigmccraig I found a race condition when our StreamVideo component is remounted to cause pip mode state to be not changed. This is fixed in [@stream-io/video-react-native-sdk-1.10.7](https://github.com/GetStream/stream-video-js/releases/tag/%40stream-io%2Fvideo-react-native-sdk-1.10.7)

Could you try this version it should fix your issue. Feel free to reopen this issue if it's not solved with this release.

**Comment by mccraigmccraig** [comment]
oh, hey @santhoshvai  - we just upgraded to 1.10.6 today... guess I'll try 1.10.7 tomorrow then :)

**Comment by mccraigmccraig** [comment]
hi @santhoshvai , I just tried with [@stream-io/video-react-native-sdk-1.10.7](https://github.com/GetStream/stream-video-js/releases/tag/%40stream-io%2Fvideo-react-native-sdk-1.10.7) - and ths issue is unfortunately not fixed

I noted one additional thing this time - which is that after returning from PiP, with the in-call controls missing, if I then pull down the notification shade and tap on the call-in-progress banner then I get the in-call controls back

https://www.loom.com/share/af49703c53674f8a8c4aa0957fe25b7e

**Comment by oliverlaz** [comment]
Hi @mccraigmccraig, following up on this issue. Do you still experience it even after upgrading to our most recent SDK version?

**Comment by oliverlaz** [comment]
Hi @mccraigmccraig, I'm closing this issue due to inactivity. I hope you were able to resolve the issue in the meantime.
If it persists, please let us know by creating a new issue or reopening this one.
